name: CI_FTB

on:
  push:
    branches: 
      - main
      - Dev_FTB
  pull_request:
    branches: 
      - main
      - Dev_FTB

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Bonjour le monde !

      - name: Run a multi-line script
        run: |
          echo Le site de construction
          echo  de la plus belle voiture !
        
      - name: Run linter
        run: npx eslint --ext "**/*.js"
